version: '3'

services:
  app:
    build: .
    container_name: ahmedov_container
#    env_file:
#      - .env.dev
    command: bash -c "python3 manage.py migrate --run-syncdb && python3 manage.py initadmin && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/Ahmedov/
    ports:
      - "8080:8000"

#    depends_on:
#      - db
#    environment:
#      - POSTGRES_HOST=db
#      - POSTGRES_DB=postgres
#     ports:
#       - 8000:8000

